### ISSUE TITLE
Unexpected token ':' while building

### ISSUE THREAD

**Issue by sulabh9999** [Spayker/rn-miband-connector#15] opened 2022-01-18 17:47 UTC
![Screenshot_20220118-230708](https://user-images.githubusercontent.com/6996776/149990383-147a21ad-a89c-4b82-8d7b-fb03f65919fc.png)

Tech Stack:
node: v14.16.0
react-native-cli: 2.0.1
react-native: 0.61.2

command:
- npm start
- react-native run-android

**Comment by Spayker** [comment] 2022-01-21 10:16
Node looks much newer seems. Does it happen with 10-th version too?

**Comment by sulabh9999** [comment] 2022-01-24 16:56
I have used both node version v10.24.1 & v11.14.0, downgraded react native to:
- react-native-cli: 2.0.1
- react-native: 0.61.5

still having same issue. Please help.

**Comment by Spayker** [comment] 2022-01-31 19:24
after short email conversation I assume the issue is solved already, closing it...

**Closed as completed by Spayker** 2022-01-31 19:24 UTC
